apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kyanos
  namespace: kyanos
  labels:
    app: kyanos
spec:
  selector:
    matchLabels:
      app: kyanos
  template:
    metadata:
      labels:
        app: kyanos
    spec:
      # Target only the specific node
      nodeSelector:
        kubernetes.io/hostname: gke-k8s-central-stg--np-cntr-xcntr-sp-7bd87fcc-vwzn
      hostPID: true
      hostNetwork: true
      tolerations:
        - operator: Exists
      containers:
        - name: kyanos
          image: IMAGE_PLACEHOLDER
          command:
            - kyanos
          args:
            - watch
            - http
            - --header
            - "X-B3-Sampled: 1"
            - --side
            - server
            - --gcs-bucket
            - GCS_BUCKET_PLACEHOLDER
            - --gcs-service-name
            - stg-edge-proxy
            - --gcs-deployment-id
            - stg-central
            - --gcs-upload-interval
            - 3m
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys-kernel
              mountPath: /sys/kernel
              readOnly: true
            - name: sys-fs-bpf
              mountPath: /sys/fs/bpf
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: run-containerd
              mountPath: /run/containerd
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: sys-kernel
          hostPath:
            path: /sys/kernel
        - name: sys-fs-bpf
          hostPath:
            path: /sys/fs/bpf
        - name: proc
          hostPath:
            path: /proc
        - name: run-containerd
          hostPath:
            path: /run/containerd
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyanos
